### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by LvledPanic**
I added in the ability to turn on/off rounding for percentages.

### CODE REVIEW

**Comment by juviasuisei** [comment]
Doesn't work. So far, you're showing the same symptoms I did when first attempting this. I tested this by running it against my in-game data on my local staging and it offers far more in a single 25% than the game does. I've found that the in-game rounding with % is very erratic/unpredictable / I didn't have the patience to figure out what it's doing because it is very inconsistent.

As an example, my BoS is 11.49M. I had 6.31e25 relics and at 25% with rounding, your code recommends BoS with 14.03M levels for 1.58e25 relics. In game 25% with rounding only does 8.5M levels for 6.13e24 cost.

**Comment by LvledPanic** [comment]
you sure? I just tested it with those numbers and it gave me 8.51m

**Comment by LvledPanic** [comment]
image

**Comment by LvledPanic** [comment]
image

**Comment by LvledPanic** [comment]
14.03 is what it gives with rounding off.

**Comment by LvledPanic** [comment]
oh lol, I see, The highlighting is wrong when it first loads. Click on the "rounding on" before executing. It does work, I tested it pretty thoroughly using my ingame data.

**Pull request closed without merging**
